### ISSUE TITLE
数据更新逻辑

### ISSUE THREAD

**Issue by rebron1900** [lizheming/doumark-action#6]
请问数据的更新逻辑是怎么样的呢？
我douban那边标记更新好几天了，但是通过doumark抓取的数据还没有更新。

**Comment by lizheming** [comment]
这个是你自己 action 写的 `cron` 指定的，action 本身只负责数据抓取逻辑的。另外只同步新增，如果先 mark 了，同步过来了，再修改了，这个我们暂时没有同步。

**Comment by lizheming** [comment]
我看你最近两周 Action 都执行失败了，https://github.com/rebron1900/doumark-action/actions

查了下原因，原来是你的 Action 配置写的有问题 https://github.com/rebron1900/doumark-action/blob/master/.github/workflows/douban.yml#L19-L20 你这两个写错了，应该是 type=movie format=json .... 

已经提 PR 了 https://github.com/rebron1900/doumark-action/pull/1

**Comment by rebron1900** [comment]
阿，不好意思，太尴尬了

**Comment by rebron1900** [comment]
https://github.com/rebron1900/logseq/blob/main/.github/workflows/douban.yml
不过大佬。我现在用的这个库，我刚刚检查了一下配置文件好像是正确的。

**Comment by lizheming** [comment]
地址 404 了

**Comment by rebron1900** [comment]
我这个库是私有库，配置文件我复制在下面。

```yml
# .github/workflows/douban.yml 123
name: douban
on: 
  schedule:
    - cron: "*/30 * * * *"
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: backup data files
      run: |
        mv ./assets/douban/book.json ./assets/douban/book_$(date +%Y-%m-%d).json.bak
        mv ./assets/douban/music.json ./assets/douban/music_$(date +%Y-%m-%d).json.bak
        mv ./assets/douban/movie.json ./assets/douban/movie_$(date +%Y-%m-%d).json.bak

    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: trax.long
        type: movie
        format: json
        dir: ./assets/douban

    - name: music
      uses: lizheming/doumark-action@master
      with:
        id: trax.long
        type: music
        format: json
        dir: ./assets/douban

    - name: book
      uses: lizheming/doumark-action@master
      with:
        id: trax.long
        type: book
        format: json
        dir: ./assets/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v8
      with:
        message: 'chore: update douban data'
        add: './assets/douban'
```
